import Head from "next/head";
import classNames from "classnames";
import { Header } from "@components/Common/Header";

import styles from "./Layout.module.scss";

type LayoutProps = {
  children: React.ReactNode;
};

const siteTitle = "Probemas";

export const LayoutComponent: React.FC<LayoutProps> = ({ children }) => {
  const layoutClassName = classNames(`${styles.layout}`);

  return (
    <div className={layoutClassName}>
      <Head>
        <title>{siteTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='container'>{children}</main>
    </div>
  );
};

LayoutComponent.displayName = "Layout";
